name: Generate Terraform README docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/modules/**/*.md'
      - '.github/workflows/documentation.yml'

permissions: {}

jobs:
  docs:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.0.0 # v1.0.0
      with:
        find-dir: terraform/modules
        output-file: README.md
        output-method: inject
        git-push: "true"
